### ISSUE TITLE
Enhance the current testing for autocomplete component with Keyman api data

### ISSUE THREAD

**Issue by IanSeng** [eddieantonio/predictive-text-studio#150]
# Background 
- The test is not able to mock the indexedDB to do a through e2e testing for the component with the Keyman api data
- The testing code is currently being commented out

### Possible solution
- [ ] Clear out existing data IndexedDB and input a mock data to isolate the test with actual data.

**Comment by eddieantonio** [comment]
I don't understand the context of this issue anymore, so I'm marking it as `wontfix`. Can be reopened in the future.
