### ISSUE TITLE
Landing page should display "Continue" instead of "upload"

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#165]
Instead of an "upload" button at the bottom of the landing page, the user should:

 1. type the name of their language; any name should do
 2. upload an Excel file or a Google Sheet URL

Once **both** steps are completed, they can click the "continue" button and go to the "languages" page and click on "Download KMP"!

**Comment by IanSeng** [comment]
> **th** steps are completed, they can click the "continue" button and go to the "languages" page and click on

Should the "continue" button being disable if the user did not upload the file or enter the language?

**Comment by eddieantonio** [comment]
> Should the "continue" button being disable if the user did not upload the file or enter the language?

YES! Absolutely! However, if there already is data for them (they already have a package), they should be able to press continue.
