### ISSUE TITLE
Create Figma wireframe(s)

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#18]
![Landing page](https://user-images.githubusercontent.com/2294397/93635953-54c55400-f9b0-11ea-9df7-4a32ebdbea5b.png)
![Basic info page](https://user-images.githubusercontent.com/2294397/93635950-53942700-f9b0-11ea-9f01-9a104314a2e5.png)
![Dictionary sources page](https://user-images.githubusercontent.com/2294397/93635948-5262fa00-f9b0-11ea-94e9-43e6222f550f.png)

**Comment by pranavnarang** [comment]
Link to Figma project: https://www.figma.com/file/0ifTqGA2I3Y216eCJxh1rr/Keyman-Predictive-Text?node-id=0%3A1
