### ISSUE TITLE
Simplify the bottom of the landing page

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#180]
The current landing page is WILD!

![Landing page as of 2020-12-08](https://user-images.githubusercontent.com/2294397/101535903-88cc6780-3956-11eb-812e-259af2645ec1.png)

It needs to provide the smoothest experience for users to get started with Predictive Text Studio

Here's what I think it should display, in ASCII art!

```
Step 1: What is the name of your language?
[  <language name dropdown with autocomplete>  ]

Step 2: Add a word list (help)
    [ Upload File | From Google Sheets URL ]

  |                                         |
  | Drag and drop an Excel .xlsx file here! |
  |                    or                   |
  |            [ Browse file... ]           |
  |                                         |
  |                                         |

[                   Continue                  ]
```

 - [x] remove the download KMP button (replace with continue button; see #165)
 - [x] split button for uploading from Excel or from a Google Sheets spreadsheet
 - [x] No more BCP-47! It should ask the language name. It will try to match with the most appropriate BCP-47 tag in the background using the Keyman API
 - [x] ~~links to an explanation of what a "word list" actually is~~ (moved to #203)

**Comment by zprobs** [comment]
@eddieantonio What is the status of PR #165 ? Do you plan on merging it and should I build on top of it?

**Comment by eddieantonio** [comment]
Yes, please build off #165!

It might be stale though; this issue might need to be split into multiple pieces as well :/
