### ISSUE TITLE
Support selecting columns from uploaded spreadsheets

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#201]
When a spreadsheet (Excel or Google Sheets) is uploaded, it will likely not be in our ideal format, namely, first column for "word" and second column for "count".

Allow the user to select which column from their spreadhseet to use as the word column and which should be the count column.

Predicitve Text Studio should try to make an educated guess by default

**Comment by ChrisChrisLoLo** [comment]
Blocked by #257, since I'm assuming we need to make changes on a source by source basis
