### ISSUE TITLE
Investigate intermediate error reporting

### ISSUE THREAD

**Issue by ChrisChrisLoLo** [eddieantonio/predictive-text-studio#243]
We want a way to be able to throw errors and report issues in our code without banking on the browser's console. This is due to concerns about the way browsers handle console logging, along with the memory implications that come with them.

As this project expands in complexity in its logic, it may be worthwhile to implement integration to error tracking software, such as Sentry or Rollbar. These tools can help us developers pinpoint errors when they occur.

Investigate what would be required to set up error tracking software integration. If the set up is fairly small, consider adding it to the codebase.

Additional static analysis tools, such as the Typescript type checker, may also prove useful in cutting down on bugs.

**Comment by ChrisChrisLoLo** [comment]
Do you think having logging only in the development build be a fair tradeoff?

We could perhaps only log in to a conditional block like this:
https://github.com/sveltejs/svelte/issues/4660

This way the client does have to worry about their client having their console logged up

**Comment by eddieantonio** [comment]
I had not considered that! That actually would be a good tradeoff!

An idea I have that we could explore:

We could the existing [Rollup replace plugin](https://github.com/rollup/plugins/tree/master/packages/replace#readme) to add a `DEBUG` or `DEVELOPMENT` flag that is only set to `true` in development. Then it could do `console.error` or perhaps even our owm custom logging function.

Here's a module idea I have (will need to be refined):

```typescript

declare const DEVELOPMENT: boolean;

let logError: (err: Error, msg: string) => void;

if (DEVELOPMENT) {
  logError = (err: Error, msg: string) => {
    console.error(msg, err);
  };
} else {
  logError = () => {/* do nothing */};
}

export {logError};
```
