### ISSUE TITLE
Update integration test for uploading file 

### ISSUE THREAD

**Issue by IanSeng** [eddieantonio/predictive-text-studio#27]
Update current integration test for uploading function whenever we are able to parse the xlsf file

**Comment by eddieantonio** [comment]
This article might be useful for the implementer: https://dev.to/viveknayyar/e2e-testing-of-excel-downloads-with-cypress-21fb

**Comment by eddieantonio** [comment]
Note, this overlaps with #32. Perhaps they are both the same issue...?
