### ISSUE TITLE
Add support to enter word and count manually

### ISSUE THREAD

**Issue by jienius** [eddieantonio/predictive-text-studio#37]
* Users should be able to create a 'Direct Entry' source.

* When users select 'Direct Entry' as their source type, a table should appear with three columns (word, word count, actions) and one 'new row'.

* Each row will have one input field for the word, one optional input field for the word count, and one 'delete' icon.

  * Users can edit values for existing rows by selecting the input field.

  * When users select a row, the styling of the row should change to indicate it has been selected.

  * Users can type in a word into a new row and when they do another new row should appear below automatically.

  * Words have to be strings and cannot be empty.

  * Word counts have to be > 0 or empty.

  * Clicking the delete icon will remove the appropriate row from the table.

 * Users can enter a name for the Direct Entry Table via a text input field.

* The table will automatically save periodically and will have a manual save button.

* The table has to have at least one valid row to be saved or added.

**Comment by xqiu1** [comment]
It's related to issue #124
