### ISSUE TITLE
Generate .kmp file for the dictionary

### ISSUE THREAD

**Issue by jienius** [eddieantonio/predictive-text-studio#40]

**Comment by eddieantonio** [comment]
**Blocked by #47**
**Blocked by #51**

A `.kmp` is a renamed `.zip` file with **at least** the following files:

 - `kmp.json` — a model info file
 - `{model_id}.model.js` — the compiled code generated by the `@predictive-text-studio/lexical-model-compiler`

Attached is an example:

[nrc.en.mtnt.model.zip](https://github.com/eddieantonio/predictive-text-studio/files/5250695/nrc.en.mtnt.model.zip)

Useful docs:
 - https://help.keyman.com/developer/cloud/package-version/1.0/
 - https://help.keyman.com/developer/current-version/reference/file-types/kmp
 - https://help.keyman.com/developer/cloud/model_info/1.0/
