### ISSUE TITLE
Find an alternate Excel reading library 🙃

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#62]
As noted in #61, `read-excel-library` is... problematic. Here are the requirements for a library:

 - [x] runs in the browser
 - [x] does not pull in Node.JS dependencies
 - [x] has TypeScript defintions
 - [x] consumes an ArrayBuffer or a Uint8Array

**Comment by eddieantonio** [comment]
`SheetJS` provides all the above features, but is a bit too bloated for my tastes; @jienius suggests [exceljs](https://github.com/exceljs/exceljs). I'll take a look!

**Comment by jienius** [comment]
> `SheetJS` provides all the above features, but is a bit too bloated for my tastes; @jienius suggests [exceljs](https://github.com/exceljs/exceljs). I'll take a look!

I did some investigation, looks like they broke something in the latest version, I checkout 3.5.0 and it worked out just fine.
No idea when or are they even going to fix it though
This issue looks related https://github.com/exceljs/exceljs/issues/1098

**Comment by jienius** [comment]
Looks like they broke it in 4.0 upgrade, all 3.x versions works
