### ISSUE TITLE
Create mockups/wireframes of managing dictionary sources

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#92]
We need to figure out how dictionary sources will be added, edited, and managed. This is the "sources" tab, or the third page in the mockups.

**Comment by ChrisChrisLoLo** [comment]
Could I have the link to this specific mockup? I think this is relevant for #201

**Comment by eddieantonio** [comment]
@ChrisChrisLoLo here are the complete mockups! https://www.figma.com/file/0ifTqGA2I3Y216eCJxh1rr/Keyman-Predictive-Text?node-id=0%3A1
